export const INCREMENT_STARNUM = 'INCREMENT_STARNYM';
export type INCREMENT_STARNUM = typeof INCREMENT_STARNUM;

export const DECREMENT_STARNUM = 'DECREMENT_STARNUM';
export type DECREMENT_STARNUM = typeof DECREMENT_STARNUM;
